/****************************************************************************
 *                                                                          *
 *  Author : lukasz.iwaszkiewicz@gmail.com                                  *
 *  ~~~~~~~~                                                                *
 *  License : see COPYING file for details.                                 *
 *  ~~~~~~~~~                                                               *
 ****************************************************************************/

#include "motor.h"
#include <msp430.h>
#include <driverlib.h>
#include <stdlib.h>
#include <ucs.h>

#define PERIOD 0xfff
#define STEPS 512
#define CLK_FREQ 10000000
#define MICROSTEP_MIN_DELAY 128

/**
 * Anything between 0 to 511.
 */
static uint16_t currentRelativeMicrostep = 0;
static uint16_t currentAbsoluteMicrostep = 0;

/**
 * Sine table generated by the python script included in this source code (build directory). Sine and the latter consine
 * tables are used for generating proper voltges (PWMs actually) for motor windings.
 */
#include "functions.h"

/**
 * From 0 to PERIOD (including).
 */
void setWinding1 (int power)
{
        TA0CCR1 = PERIOD - abs (power);
//        TA0CCR1 = 0;

        if (power >= 0) {
                P1OUT &= ~GPIO_PIN0;
        }
        else {
                P1OUT |= GPIO_PIN0;
        }
}

void setWinding2 (int power)
{
        TA0CCR2 = PERIOD - abs (power);
//        TA0CCR2 = 0;

        if (power >= 0) {
                P1OUT &= ~GPIO_PIN1;
        }
        else {
                P1OUT |= GPIO_PIN1;
        }
}

/**
 * Initialize timer as PWM generator.
 */
void initPWM (void)
{
        GPIO_setAsPeripheralModuleFunctionOutputPin (GPIO_PORT_P1, GPIO_PIN2 | GPIO_PIN3);
//        GPIO_setAsOutputPin (GPIO_PORT_P6, GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN3);
        GPIO_setAsOutputPin (GPIO_PORT_P1, GPIO_PIN0 | GPIO_PIN1);

        /*
         * Konfiguracja pierwszego timera typu A. Wybór źródła sygnału zegarowego za pomocą :
         * TASSEL_0 : TAxCLK sygnał zewnętrzny. ?
         * TASSEL_1 : ACLK sygnał wewnętrzny. Auxiliary clock.
         * TASSEL_2 : SMCLK sygnał wewnętrzny. Subsystem master clock.
         * TASSEL_3 : INCLK sygnał zewnętrzny. ?
         *
         */
        TA0CTL |= TASSEL_2 |

        /*
         * Pierwszy divider. Możliwe opcje to:
         * ID_0 : /1
         * ID_1 : /2
         * ID_2 : /4
         * ID_3 : /8
         */
        ID_0 |

        /*
         * Tryb działania
         * Timer mode control: 0 - Stop
         *
         * Timer mode control: 1 - Up to TAxCCR0 i znów od 0. W tym przypadku używany jest tylko TAxCCR0 (Timer_Ax Capture/Compare 0).
         *                         Kiedy timer dojdzie do wartości TAxCCR0, to ustawiany jest bit CCIFG w rejestrze TAxCCTL0. Natomiast
         *                         zaraz potem, kiedy  tylko timer się wyzeruje µC ustawia bit TAIFG w rejestrze TAxCTL (Timer_Ax Control).
         *                         Czyli te zdarzenia następują zaraz po sobie.
         *
         * Timer mode control: 2 - Continuous up, czyli liczy do 0xffff i znów od zera. Kiedy dojdzie do 0xffff, to ustawia TAIFG w TAxCTL
         *                         (Timer_Ax Control), tak samo jak w poprzednim wypadku.
         *
         * Timer mode control: 3 - Up/Down, cyzli od 0 do TAxCCR0 i potem do 0 i w kółko.
         *
         */
        MC_1;

        /*
         * Dalszy podział sygnału zegarowego. Możliwe wartości:
         * TAIDEX_0 : /1
         * TAIDEX_1 : /2
         * TAIDEX_2 : /3
         * TAIDEX_3 : /4
         * TAIDEX_4 : /5
         * TAIDEX_5 : /6
         * TAIDEX_6 : /7
         * TAIDEX_7 : /8
         */
        TA0EX0 = TAIDEX_0;

        // Można ustawić aktualny stan timera, ale nie trzeba.
        TA0R = 0;

        /*
         * Reset timera. Zawsze wykonać po ustawieniu dzielników sygnału zegarowego.
         */
        TA0CTL |= TACLR;


/*---------------------------------------------------------------------------*/

        TA0CCR0 = PERIOD;

        TA0CCR1 = (PERIOD / 2);
        TA0CCTL1 |= OUTMOD_3; // Toggle


        TA0CCR2 = (PERIOD / 2);
        TA0CCTL2 |= OUTMOD_3; // Toggle
}

/**
 * We have 5120 steps fullscale. TODO consider ramping up. If it is necessary, or not and what ease function to use (cosine? linear?)
 * Caution this function invalidates the absolute position variable, so moveAbsolute won't work properly after call to either moveRightRelative
 * or moveLeftRelative.
 */
void moveRightRelative (uint16_t microSteps)
{
        while (microSteps) {
                ++currentRelativeMicrostep;

                if (currentRelativeMicrostep >= 512) {
                        currentRelativeMicrostep = 0;
//                        ++currentStep;
//
//                        if (currentStep >= 10) {
//                                currentStep = 0;
//                        }
                }

                setWinding1 (COSINE[currentRelativeMicrostep]);
                setWinding2 (SINE[currentRelativeMicrostep]);

                // Delay
                for (int i = 0; i < MICROSTEP_MIN_DELAY; ++i)
                        ;

                --microSteps;
        }
}

/**
 * \see moveRightRelative
 */
void moveLeftRelative (uint16_t microSteps)
{
        while (microSteps) {
                --currentRelativeMicrostep;

                if (currentRelativeMicrostep == 0) {
                        currentRelativeMicrostep = STEPS - 1;
//                        --currentStep;
//
//                        if (currentStep == 0) {
//                                currentStep = 9;
//                        }
                }

                setWinding1 (COSINE[currentRelativeMicrostep]);
                setWinding2 (SINE[currentRelativeMicrostep]);

                // Delay
                for (int i = 0; i < MICROSTEP_MIN_DELAY; ++i)
                        ;

                --microSteps;
        }
}

/**
 *
 */
void moveAbsolute (uint16_t microSteps)
{
        currentAbsoluteMicrostep = microSteps - currentAbsoluteMicrostep;

        if (currentAbsoluteMicrostep > 0) {
                moveRightRelative (currentAbsoluteMicrostep);
        }
        else {
                moveLeftRelative (currentAbsoluteMicrostep);
        }
}

void rotate (void)
{
        while (1) {

                for (int j = 0; j < STEPS; ++j) {

                        setWinding1 (COSINE[j]);
                        setWinding2 (SINE[j]);

                        // Delay
                        for (int i = 0; i < 1024; ++i)
                                ;
                }
        }
}
